version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - redis
      - redis-exporter

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    depends_on:
      - redis
    command:
      - '--redis.addr=redis:6379'

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mssql#2023
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards/dashboard.json:/etc/grafana/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus