version: '3.7'
services:
  couchbase:
    image: couchbase/server:latest
    container_name: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - couchbase_data:/opt/couchbase/var
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
volumes:
  couchbase_data:'
  \'