version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mssql#2023
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data