replicaCount: 1

image:
  repository: docker.io/docker/hub
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: docker-hub-service
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

resources: {}